### ISSUE TITLE
Error when encoding in compute

### ISSUE THREAD

**Issue by tmasunda** [folksable/blurhash_ffi#17]
Good day

I am getting the following error when I call the following in a compute method:
hash = await BlurhashFFI.encode(imageProvider);

Error: BlurException: #0      BlurhashFFI.encode (package:blurhash_ffi/blurhash.dart:88:7)

What could be the cause? Please assist.

**Comment by dhikshith12** [comment]
do not use it in `compute`, it already uses a new isolate to not block the main UI isolate, i think that might be the reason.
