### ISSUE TITLE
Why are you using an intermeditate Isolate?

### ISSUE THREAD

**Issue by escamoteur** [folksable/blurhash_ffi#18]
I just got curious, as FFI is pretty fast, why do you use an additional Isolate? Would otherwise the UI block?

**Comment by dhikshith12** [comment]
Dart FFI itself does not introduce threading or automatically manage concurrency differently from standard Dart code. Therefore, it does not run on a separate thread by default; it runs on the same UI isolate unless you explicitly manage concurrency.

**Comment by escamoteur** [comment]
Ah, yes makes sense, thanks.
