### ISSUE TITLE
Dart Implementation

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [folksable/blurhash_ffi#9]
Hey,

is it somehow possible to make this package also available to Dart?

**Comment by dhikshith12** [comment]
Hey @JoshiJoshiJoshi, I don't clearly understand what you mean by "available to Dart"

I'm assuming if you want to use this dart package you can use it by adding it to you projects from pub.dev
[https://pub.dev/packages/blurhash_ffi](https://pub.dev/packages/blurhash_ffi)

**Comment by dhikshith12** [comment]
Flutter SDK is required for this package because it utilizes some of the ui functionality in decoding the image from blurhash String however encoding is free of any flutter specific code.

**Comment by dhikshith12** [comment]
[blurhash_dart](https://pub.dev/packages/blurhash_dart) is a good package that's available in dart as well as flutter, i think they are using image package to do image decoding, but this package choose to have minimum dependencies.
